# Generated by Django 3.1.2 on 2020-11-02 07:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_id', models.IntegerField(verbose_name='Vehicle_ID')),
                ('package_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='Package_ID')),
                ('travel_type_id', models.IntegerField(verbose_name='Travel_Type_ID')),
                ('from_area_id', models.IntegerField(verbose_name='From_ID')),
                ('to_area_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='To_ID')),
                ('from_city_id', models.IntegerField(verbose_name='From_City')),
                ('to_city_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='To_City')),
                ('from_date', models.DateTimeField(verbose_name='From_Date')),
                ('to_date', models.DateTimeField(blank=True, null=True, verbose_name='To_Date')),
                ('online_booking', models.BooleanField(default=False, verbose_name='Online_Booking')),
                ('mobile_site_booking', models.BooleanField(default=False, verbose_name='Mobile_Booking')),
                ('from_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='From_Lat')),
                ('from_long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='From_Long')),
                ('to_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='To_Lat')),
                ('to_long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='To_Long')),
                ('car_cancellation', models.BooleanField(default=False, verbose_name='Car_Cancelled')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
